### ISSUE TITLE
Action Row Error

### ISSUE THREAD

**Issue by JasonWu55** [Tolga1452/djs-v13-to-v14#1]
`const buy_row = new client.discord.ActionRowBuilder().addComponents(
            new client.discord.SelectMenuBuilder()
              .setCustomId("selectc")
              .setPlaceholder("選擇購買項目")
              addOptionss([
                {
                  label: "Discord Nitro",
                  value: "nitro",
                  emoji: "<:nitro2:1011604013986361374>",
                },
                {
                  label: "Minecraft",
                  value: "mc",
                  emoji: "<:minecraft:1002252456132104262>",
                }
            ])
          )`
addOptionss should be .addOptions

**Comment by Tolga1452** [comment]
~~It's a bug with your code. The system doesn't fix your code, it just converts v13 definitions to v14.~~

**Edit:** I saw my code replaces `.addOption` with `addOptions`. I will delete this part of code because this may causes some issues like this.

**Comment by Tolga1452** [comment]
It's fixed now.
